name: Rust

on:
  push:
    branches: [ "master", "in-dev" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use rust nightly
      run: rustup update nightly && rustup default nightly
    - name: Check fmt
      run: rustup component add rustfmt && cargo fmt --check
    - name: Build
      run: cargo build --verbose --release
    # Right now there are no tests specified
    # - name: Run tests
    #   run: cargo test --verbose
    - name: Upload release build to Discord
      run: .github/workflows/discord_upload.sh
      shell: bash
      env:
        DISCORD_RELEASE_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
